create table if not exists public.draws (
  id bigint generated by default as identity primary key,
  draw_date date not null unique,
  numbers smallint[] not null,
  chance smallint not null,
  created_at timestamptz not null default now(),
  constraint draws_five_numbers check (cardinality(numbers) = 5),
  constraint draws_chance_range check (chance between 1 and 10)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_grids (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  numbers smallint[] not null,
  chance smallint not null,
  method text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.saved_grids enable row level security;

create policy "Users read own profile"
on public.profiles for select
using (auth.uid() = id);

create policy "Users update own profile"
on public.profiles for update
using (auth.uid() = id);

create policy "Users manage own grids"
on public.saved_grids for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
