-- LotoLab IA — Migration 0001 : tirages + pipeline d'import
-- Tables : draws, import_jobs, import_quarantine, sync_logs
-- Aucune donnée n'est insérée : la base démarre vide et se remplit via le
-- collecteur officiel ou l'import manuel contrôlé.

-- Fonction utilitaire : nombre d'éléments distincts d'un tableau
create or replace function public.array_distinct_count(arr anyarray)
returns integer
language sql
immutable
set search_path = ''
as $$
  select count(distinct x)::integer from unnest(arr) as t(x);
$$;

-- Fonction utilitaire : mise à jour automatique de updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tirages officiels
-- ---------------------------------------------------------------------------
create table if not exists public.draws (
  id bigint generated by default as identity primary key,
  draw_date date not null,
  draw_type text not null default 'loto',
  numbers smallint[] not null,
  chance smallint not null,
  jackpot_euros bigint,
  source text not null default 'manual',
  source_url text,
  retrieved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint draws_unique_date_type unique (draw_date, draw_type),
  constraint draws_five_numbers check (cardinality(numbers) = 5),
  constraint draws_numbers_range check (1 <= all(numbers) and 49 >= all(numbers)),
  constraint draws_numbers_distinct check (public.array_distinct_count(numbers) = 5),
  constraint draws_chance_range check (chance between 1 and 10),
  constraint draws_type_known check (draw_type in ('loto'))
);

create index if not exists idx_draws_date_desc on public.draws (draw_date desc);
create index if not exists idx_draws_numbers on public.draws using gin (numbers);

create trigger trg_draws_updated_at
  before update on public.draws
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Historique des imports
-- ---------------------------------------------------------------------------
create table if not exists public.import_jobs (
  id bigint generated by default as identity primary key,
  source text not null,
  source_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'success', 'partial', 'failed')),
  triggered_by text not null default 'scheduler'
    check (triggered_by in ('scheduler', 'manual', 'admin', 'retry')),
  triggered_by_user uuid,
  started_at timestamptz,
  finished_at timestamptz,
  draws_found integer not null default 0,
  draws_imported integer not null default 0,
  draws_skipped integer not null default 0,
  draws_quarantined integer not null default 0,
  attempt integer not null default 1,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists idx_import_jobs_created on public.import_jobs (created_at desc);
create index if not exists idx_import_jobs_status on public.import_jobs (status);

-- ---------------------------------------------------------------------------
-- Quarantaine des données incohérentes
-- ---------------------------------------------------------------------------
create table if not exists public.import_quarantine (
  id bigint generated by default as identity primary key,
  job_id bigint references public.import_jobs(id) on delete set null,
  raw_data jsonb not null,
  reason text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_quarantine_status on public.import_quarantine (status, created_at desc);

-- ---------------------------------------------------------------------------
-- Journal des synchronisations
-- ---------------------------------------------------------------------------
create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  job_id bigint references public.import_jobs(id) on delete cascade,
  level text not null default 'info'
    check (level in ('debug', 'info', 'warning', 'error')),
  message text not null,
  context jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_sync_logs_job on public.sync_logs (job_id, created_at);
create index if not exists idx_sync_logs_created on public.sync_logs (created_at desc);
