-- LotoLab IA — Migration 0002 : utilisateurs, grilles, préférences,
-- notifications, droits Premium.

-- ---------------------------------------------------------------------------
-- Profils (miroir de auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Création automatique du profil à l'inscription
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', null))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Rôle admin accessible aux politiques RLS sans récursion
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------------------
-- Grilles enregistrées
-- ---------------------------------------------------------------------------
create table if not exists public.saved_grids (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  numbers smallint[] not null,
  chance smallint not null,
  method text not null,
  seed bigint,
  created_at timestamptz not null default now(),
  constraint saved_grids_five_numbers check (cardinality(numbers) = 5),
  constraint saved_grids_numbers_range check (1 <= all(numbers) and 49 >= all(numbers)),
  constraint saved_grids_numbers_distinct check (public.array_distinct_count(numbers) = 5),
  constraint saved_grids_chance_range check (chance between 1 and 10)
);

create index if not exists idx_saved_grids_user on public.saved_grids (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Numéros favoris
-- ---------------------------------------------------------------------------
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  number smallint not null,
  is_chance boolean not null default false,
  created_at timestamptz not null default now(),
  constraint favorites_unique unique (user_id, number, is_chance),
  constraint favorites_number_range check (
    (is_chance = false and number between 1 and 49)
    or (is_chance = true and number between 1 and 10)
  )
);

create index if not exists idx_favorites_user on public.favorites (user_id);

-- ---------------------------------------------------------------------------
-- Préférences utilisateur
-- ---------------------------------------------------------------------------
create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  theme text not null default 'system' check (theme in ('system', 'light', 'dark')),
  language text not null default 'fr',
  notifications_enabled boolean not null default false,
  notify_new_draw boolean not null default false,
  notification_weekly_limit smallint not null default 3
    check (notification_weekly_limit between 0 and 10),
  consent_ads boolean not null default false,
  consent_analytics boolean not null default false,
  consent_updated_at timestamptz,
  updated_at timestamptz not null default now()
);

create trigger trg_user_preferences_updated_at
  before update on public.user_preferences
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'info'
    check (kind in ('info', 'new_draw', 'premium', 'system')),
  title text not null,
  body text not null,
  sent_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user on public.notifications (user_id, created_at desc);
create index if not exists idx_notifications_unread on public.notifications (user_id) where read_at is null;

-- ---------------------------------------------------------------------------
-- Droits Premium
-- ---------------------------------------------------------------------------
create table if not exists public.premium_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product text not null check (product in ('monthly', 'yearly', 'lifetime', 'trial')),
  platform text not null check (platform in ('google_play', 'app_store', 'stripe', 'manual')),
  status text not null default 'active'
    check (status in ('active', 'expired', 'revoked', 'refunded')),
  started_at timestamptz not null default now(),
  expires_at timestamptz,
  receipt_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_premium_user on public.premium_entitlements (user_id, status);

create trigger trg_premium_updated_at
  before update on public.premium_entitlements
  for each row execute function public.set_updated_at();

-- Un utilisateur est Premium si un droit actif non expiré existe
create or replace function public.has_premium(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.premium_entitlements
    where user_id = uid
      and status = 'active'
      and (expires_at is null or expires_at > now())
  );
$$;
