-- LotoLab IA — Migration 0003 : journal d'audit, contenus SEO,
-- emplacements publicitaires.

-- ---------------------------------------------------------------------------
-- Journal d'audit des actions sensibles (back-office et API admin)
-- ---------------------------------------------------------------------------
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_email text,
  action text not null,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_log_created on public.audit_log (created_at desc);
create index if not exists idx_audit_log_actor on public.audit_log (actor_id);

-- ---------------------------------------------------------------------------
-- Contenus SEO éditables depuis le back-office
-- ---------------------------------------------------------------------------
create table if not exists public.seo_contents (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  meta_description text,
  body_md text not null default '',
  published boolean not null default false,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_seo_contents_published on public.seo_contents (published, slug);

create trigger trg_seo_contents_updated_at
  before update on public.seo_contents
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Emplacements publicitaires (désactivés par défaut)
-- ---------------------------------------------------------------------------
create table if not exists public.ad_placements (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  enabled boolean not null default false,
  network text not null default 'admob' check (network in ('admob', 'none')),
  unit_id text,
  max_per_session smallint not null default 1 check (max_per_session between 0 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_ad_placements_updated_at
  before update on public.ad_placements
  for each row execute function public.set_updated_at();
